### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-3id-blockchain-utils#21]
Hey @oed - i was reading through the code here and found this line:

https://github.com/ceramicnetwork/js-3id-blockchain-utils/blob/master/src/blockchains/ethereum.js#L114

I thought it was worth raising the issue since i thought `text` might've meant to be `message`.

**Comment by oed** [comment]
Nice catch @Schwartz10! Definitely a bug!
