### ISSUE TITLE
createErc1271Link signing bug on MetaMask

### ISSUE THREAD

**Issue by PeterMPhillips** [ceramicnetwork/js-3id-blockchain-utils#29]
When attempting to link an identity-wallet to an ERC-1271 contract I get the following error from MetaMask: `Invalid parameters: must provide an Ethereum address.`

The error occurs because MetaMask checks that the account you're signing for is in MetaMask's list of accounts: https://github.com/MetaMask/eth-json-rpc-middleware/blob/master/wallet.js#L175
https://github.com/MetaMask/eth-json-rpc-middleware/blob/master/wallet.js#L249

But in `createErc1271Link` we are passing the address for the ERC1271 contract, not the address we are using to sign the message. `createErc1271Link` needs to get the selected address from the provider (`provider.selectedAddress`) and pass that value to `createEthLink` in order to generate the signature. I got this working on version 0.4.1 of `3id-blockchain-utils` with the following function:
```
async function createErc1271Link (did, address, provider, opts) {
  const selectedAddress = provider.selectedAddress || address
  const res = await createEthLink(did, selectedAddress, provider, opts)
  const chainId = await getChainId(provider)
  return Object.assign(res, {
    type: ADDRESS_TYPES.erc1271,
    address,
    chainId,
  })
}
```

However, I'm unsure what else is needed now that the code has been switched over to Typescript. Also, I'm unsure if this would create problems for other providers as I don't know whether `provider.selectedAddress` is standard across all providers.

**Comment by oed** [comment]
Thanks @PeterMPhillips Added this to our upcoming sprint. Hopefully we can get a fix released rather soon!

**Comment by zachferland** [comment]
https://github.com/ceramicnetwork/js-3id-blockchain-utils/pull/36 is merged now and implements a fix for this, thanks!

fix adds option to pass to an eoaSignAccount address option when creating a link, allows externally owned account address to be passed when ever signer requires address signing for contract account

will be release soon, closing issue now
