### ISSUE TITLE
Issues with Filecoin implementation

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-3id-blockchain-utils#34]
Building 3ID Connect an other apps using it produces the following warning:

> WARNING in ./node_modules/3id-blockchain-utils/lib/blockchains/filecoin.js 82:77-100
Critical dependency: the request of a dependency is an expression

The issue comes from this line: https://github.com/ceramicnetwork/js-3id-blockchain-utils/blob/master/src/blockchains/filecoin.ts#L9 that seems like it's importing a different module for the test environment.

Additionally, tests are failing in CI:

> FAIL  src/blockchains/__tests__/filecoin.test.ts
  ● Test suite failed to run

    CompileError: WebAssembly.Module(): Wasm decoding failed: mutable globals cannot be exported @+7693

    > 1 | import {LocalManagedProvider} from "@glif/local-managed-provider";
        | ^
      2 | import {Network} from "@glif/filecoin-address"
      3 | import {authenticate, createLink, validateLink} from "../filecoin";
      4 | import {AccountID} from "caip";

      at Object.<anonymous> (node_modules/@zondax/filecoin-signing-tools/nodejs/filecoin_signer_wasm.js:1365:20)
      at Object.<anonymous> (node_modules/@glif/local-managed-provider/dist/src/private-key-container.ts:10:22)
      at Object.<anonymous> (node_modules/@glif/local-managed-provider/dist/src/local-managed-provider.ts:5:1)
      at Object.<anonymous> (node_modules/@glif/local-managed-provider/dist/src/index.ts:1:1)
      at Object.<anonymous> (src/blockchains/__tests__/filecoin.test.ts:1:1)

cc @ukstv any idea how these could be fixed please?
Even if the warning is not an actual issue, we got developers asking about it when building apps using 3ID Connect so I'd rather avoid possible confusion with this.

**Comment by ukstv** [comment]
Fix for expression warning is in https://github.com/ceramicnetwork/js-3id-blockchain-utils/pull/37

@PaulLeCam CI: Are you sure Node v10 is a good target for CI?

**Comment by PaulLeCam** [comment]
Thanks!
About CI I think v12 would we a better target, what do you think? cc @oed @zachferland

**Comment by ukstv** [comment]
v12 feels like necromancy too to me. Current LTS is v14.

**Comment by oed** [comment]
Let's do 14 unless we have a specific reason to do 12

**Comment by zachferland** [comment]
thanks, #37 merged and change ci target -> v1, closing issue
