### ISSUE TITLE
Expected optional dependency behavior

### ISSUE THREAD

**Issue by zachferland** [ceramicnetwork/js-3id-blockchain-utils#40]
looks like npm actually installs optionalDependencies by default, they are only not in installed if you use the --no-optional flag

seems like using peerDependencies might actually get the behavior we wanted, but have to confirm/change

**Comment by oed** [comment]
@ukstv Any insight here? IIRC you moved some deps from peerDeps to optionalDeps?

**Comment by ukstv** [comment]
Have to try. Trying to work around the weird wasm-handling behavior for the last few days actually.

**Comment by ukstv** [comment]
@oed Moved this expecting proper _optionality_ in dependency-handling. Apparently, as @zachferland tells above, this is not true.

**Comment by PaulLeCam** [comment]
> seems like using peerDependencies might actually get the behavior we wanted, but have to confirm/change

AFAIK npm v6 doesn't install peer dependencies by default but v7 does

**Comment by oed** [comment]
@PaulLeCam what do you think would be an appropriate action here?

**Comment by ukstv** [comment]
The troublesome thing is CRA tries to include even dynamic dependencies here. It seems, the best course of actions is to modularise the package, and put the burden of including filecoin/polkadot/ethereum verifiers-signers to an app developer, with ehtereum being the safe default.

**Comment by PaulLeCam** [comment]
I agree removing the other signers from the package would be the easiest solution to prevent these issues, as for the burden of additional signers I guess it depends if that would need to be handled in 3ID Connect directly (easier but could be bad UX loading MBs of code in 3ID Connect), or apps could provide custom signers to 3ID Connect (puts the burden on developers).

**Comment by zachferland** [comment]
yeah agree, seem like each blockchain implementation should become a package, i guess making this a monorepo
and then you have to register each handler you want to use 

at least in 3id-connect its not a concern yet, since verification is at the remote ceramic node, so cheap to add mbs there, wont be in the iframe 

but i guess from the auth/signing side in 3id-connect, it would probably make sense to get rid of authproviders, with the current implementation of 3id-blockchain-utils these ended up only be very thin interfaces (or move into these separate packages here), and then you would similarly have to register/install whatever chains you needed support for

**Comment by zachferland** [comment]
or i guess even better, signer/verifiers are in other repos, maintained by those communities and defaults for each chain are just listed here

**Comment by PaulLeCam** [comment]
> but i guess from the auth/signing side in 3id-connect, it would probably make sense to get rid of authproviders, with the current implementation of 3id-blockchain-utils these ended up only be very thin interfaces (or move into these separate packages here), and then you would similarly have to register/install whatever chains you needed support for

So the auth providers would have to be imported and handled by the apps themselves?
I think that makes sense and would be good for apps as they likely need to keep track of the provider/auth provider changes anyways.

**Comment by ukstv** [comment]
Yes! This would eliminate EthereumAuthProvider from 3id-connect. If all of you guys are happy with this course of action, I volunteer to do this. Have to make the Filecoin stuff work, you know :)

**Comment by zachferland** [comment]
@ukstv sounds good! think just need resolve a few more things to decide exact change

>So the auth providers would have to be imported and handled by the apps themselves?
I think that makes sense and would be good for apps as they likely need to keep track of the provider/auth provider changes anyways.

@PaulLeCam do you think it makes sense to keep the authProvider interface (at least as an external), or remove entirely?  

all it really does at this point is handle "accounts/address" to caip10 account ids in the background, so that devs dont necessarily have to know about those if they are only in their own ecosystem, feels like a decent amount of friction. Also assumed that in future we may have other auth methods that are not blockchain accounts, but doesnt seem worth thinking about until we get there.

**option 1**
If removed, dev would just have to register the blockchain handlers from here they want to use, and then pass a caip10 when using 3id-connect. Then it can easily select the correct functions to use.

**option 2**
Alternatively could have the authProvider interface optionally included as part of handler modules here instead, so anyone adding chain support would likely want to add that as well for usability. With fallback to a general auth provider that does detection based on caip10. 

**option 3**
handlers here each implement blockchain detection based on provider and account/address, you register handlers you want, and then this determines caip10/handler based on that detection. Seems reasonable, but a bit unstable or best effort.

i guess all these could still keep the option to pass an authprovider, that just being the interface 3id-connect interacts with

**Comment by oed** [comment]
A few thoughts, seems like auth is a bit different from create/validate link. Here is another option:

**`did-blockchain-auth`**
- Has authentication code for all blockchains
- Doesn't require any heavy crypto libraries
- Account parameter needs to be CAIP10

**`did-blockchain-links`**
- Main library for the `createLink`/`validateLink` interface

  **`did-[blockchain]-link`**
   - Blockchain specific libraries

**Comment by ukstv** [comment]
Suggest we shuffle a bit. `did-blockchain-auth` just calls a crypto provider. So, it combines current responsibility of `createLink`, `authenticate` (from `3id-blockchain-utils`) with `AbstractAuthProvider`, `EthereumAuthProvider`. It is light-weight indeed, and exports all the necessary interfaces so that one could provide one's own blockchain-implementation as external package. Then `did-blockchain-link` contains all the heavy lifting for signature validation, and is actually only used on full node side.

Also, I currently fail to see why these are related to DID in general. Maybe `3id-blockchain-auth` and `3id-blockchain-link` or `ceramic-` prefixed. It does not click to me to have DID in the name. If there is a reason for DID-naming, please share it with me.

**Comment by oed** [comment]
The first part makes sense @ukstv 👍 

I mean they are related to DIDs in general because they can be used to link a blockchain account to any DID. We use the `authenticate` function explicitly for 3ID right now, but that might change in the future.

**Comment by ukstv** [comment]
Oops, I happen to forget DID-agnosticism of Ceramic.
